### ISSUE TITLE
Any plans on scene flow?

### ISSUE THREAD

**Issue by afterthat97** [open-mmlab/mmflow#111]
Would you provide support for scene flow algorithms like FlowNet3D, RAFT-3D, HPLFlowNet, PointPWC, etc?

**Comment by MeowZheng** [comment]
It is a very good proposal, but we suffer from a shortage of manpower, so sense flow might not be supported in 2022 H1. Any collaborations are appreciated If you are interested in it. 

Here is [a document](https://github.com/open-mmlab/mmcv/blob/master/docs/en/community/pr.md) about how to create pr to contribute code to codebases in OpenMMLab, just for your reference.

**Comment by afterthat97** [comment]
Thanks! I will take a look.
