### ISSUE TITLE
Norm the output of correlation_block

### ISSUE THREAD

**Issue by lhao0301** [open-mmlab/mmflow#115]
In this repo, the correlation output is not normalized(`scale=False` always), which is different from that in PWC & FlowNet repo. They normalize it by dimension. Hence, is it make little of importance?

https://github.com/open-mmlab/mmflow/blob/2f9871623f8b179a8920cfe067306c7d8b4848c0/mmflow/models/utils/correlation_block.py#L61-L68

**Comment by MeowZheng** [comment]
I have tested doing correlation normalization but found it made models difficult to coverage
