### ISSUE TITLE
input image size question

### ISSUE THREAD

**Issue by dialuser** [open-mmlab/mmflow#137]
Hi 

My use case involves 180x360 image frames (satellite earth data). Can I configure mmflow models to take that type of input sizes?

Thanks,
Alex

**Comment by MeowZheng** [comment]
I just suggest you might follow this [dataset cfg file](https://github.com/open-mmlab/mmflow/blob/master/configs/_base_/datasets/flyingchairs_320x448.py) to define your own dataset config, and pay more attention the `crop_size` and make sure it suits your dataset
https://github.com/open-mmlab/mmflow/blob/89b0f41695267e480ccb5d68c5dd7d8166918b6c/configs/_base_/datasets/flyingchairs_320x448.py#L36

**Comment by dialuser** [comment]
thanks.
