### ISSUE TITLE
unsupervised fine tuning

### ISSUE THREAD

**Issue by dialuser** [open-mmlab/mmflow#138]
Hi 
I wonder if it's possible to fine tune a pre-trained model on a dataset w/o flow labels, i.e., mixing supervised optical flow with unsupervised learning?  

Thanks,
Alex

**Comment by MeowZheng** [comment]
It is possible, and mmflow also has a plan to support unsupervised optical flow learning. However, suffering from the lack of developer, the progress is slow, but collaborations are appreciated If you are interested in it.
