### ISSUE TITLE
Is it possible to get optical flow from the converted RGB video?

### ISSUE THREAD

**Issue by Jockey721** [open-mmlab/mmflow#143]
After visualizing optical flow as RGB video by visualize_flow(), is it possible to get optical flow from the converted RGB video?

**Comment by MeowZheng** [comment]
please try the video demo
https://github.com/open-mmlab/mmflow/blob/master/demo/video_demo.py

**Comment by woaixueyingying** [comment]
I try the video demo,but the code runs for a while and then shows killed.What's the reason for this?
