### ISSUE TITLE
pwcnet to onnx

### ISSUE THREAD

**Issue by betterhalfwzm** [open-mmlab/mmflow#148]
```
import os
import sys
import argparse
import torch
from mmflow.apis import inference_model, init_model
from mmflow.datasets import visualize_flow, write_flow

def parser_func():
    parser = argparse.ArgumentParser()
    parser.add_argument('--config',default='configs/pwcnet/pwcnet_ft_4x1_300k_kitti_320x896.py',  help='Config file')
    parser.add_argument('--checkpoint', type=str, default='models/pwc/pwcnet_ft_4x1_300k_kitti_320x896.pth')
    parser.add_argument('--out_path', type=str, default='models/pwc/pwcnet_ft_4x1_300k_kitti_320x896.onnx')
    parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')
    parser.add_argument('--batch_size', type=int, default=1)
    args = parser.parse_args()
    os.makedirs(os.path.dirname(args.out_path), exist_ok=True)
    return args

def export_onnx():
    model = init_model(args.config, args.checkpoint, device=args.device)

    input_names = ['encoder.layers.0.layers.0.conv']
    output_names = ['decoder.decoders.level6.upfeat_layer']

    dummy_input = torch.randn(args.batch_size, 6, 320, 896).cuda()

    torch.onnx.export(model, dummy_input, args.out_path,
                      input_names=input_names, output_names=output_names, opset_version=11,
                      verbose=True)

if __name__ == '__main__':
    args = parser_func()
    export_onnx()
```

RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: numpy.ndarray

**Comment by MeowZheng** [comment]
The output of model is `ndarray` https://github.com/open-mmlab/mmflow/blob/203ea55ad8a4f99fcb394371aa0ba4423d3debcc/mmflow/models/decoders/pwcnet_decoder.py#L327-L328

Is the problem here?

**Comment by betterhalfwzm** [comment]
> The output of model is `ndarray`
> 
> https://github.com/open-mmlab/mmflow/blob/203ea55ad8a4f99fcb394371aa0ba4423d3debcc/mmflow/models/decoders/pwcnet_decoder.py#L327-L328
> 
> Is the problem here?

Yes，it works. But new error，do you have good idea?
RuntimeError: Exporting the operator grid_sampler to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

**Comment by lvhan028** [comment]
> A Tricky solution. The [Nightly-build-version pytorch](https://pytorch.org/) [>=1.12] works, which supports opset16. If tensorRT backend is wanted to be used, unfortunately, `GridSample` plugin is not supported in official latest tensorRT now and have to implement a custom plugin.

Hi, may try [mmdeploy](https://github.com/open-mmlab/mmdeploy), which already supports `grid_sampler`. 
https://github.com/open-mmlab/mmdeploy/tree/master/csrc/mmdeploy/backend_ops/tensorrt/grid_sampler
