### ISSUE TITLE
ImportError: cannot import name 'Correlation' from 'mmcv.ops'

### ISSUE THREAD

**Issue by Z-XQ** [open-mmlab/mmflow#16]
window10
cuda10.2
pytorch1.6
python3.7
mmcv1.1.5

my first try failed. is the version of mmcv too old?

error info:
ImportError: cannot import name 'Correlation' from 'mmcv.ops'

**Comment by MeowZheng** [comment]
Yes, it's too old. Please double-check [prerequisites](https://github.com/open-mmlab/mmflow/blob/master/docs/install.md#prerequisites), and MMFlow needs MMCV 1.3.15+

**Comment by Z-XQ** [comment]
Thanks for your relpy! I just built MMCV from source, and the version is 1.3.17 (newest). But I get the error info as following.

error info:
`Traceback (most recent call last):
  File "D:/code/PycharmProjects/mmflow-master/verify_install.py", line 12, in <module>
    from mmflow.apis import inference_model, init_model
  File "D:\code\PycharmProjects\mmflow-master\mmflow\apis\__init__.py", line 2, in <module>
    from .inference import inference_model, init_model
  File "D:\code\PycharmProjects\mmflow-master\mmflow\apis\inference.py", line 8, in <module>
    from mmcv.ops import Correlation
  File "d:\code\pycharmprojects\mmcv-master\mmcv\ops\__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "d:\code\pycharmprojects\mmcv-master\mmcv\ops\assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "d:\code\pycharmprojects\mmcv-master\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\Administrator\.conda\envs\mmflow\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
`

pip list:
`------------- ---------- -------------------------------------
addict        2.4.0
certifi       2021.10.8
mkl-fft       1.3.1
mkl-random    1.2.2
mkl-service   2.4.0
mmcv          1.3.17     d:\code\pycharmprojects\mmcv-master
mmflow        0.1.0      d:\code\pycharmprojects\mmflow-master
numpy         1.21.2
olefile       0.46
`

**Comment by MeowZheng** [comment]
In this [part](https://github.com/open-mmlab/mmflow/blob/master/docs/install.md#prepare-environment), we have explained the cause of this problem.
![image](https://user-images.githubusercontent.com/76149310/142161702-9e0687f9-5932-42b3-a903-71a6d8e7a85f.png)

In addition, please check out [mmcv installation documents](https://github.com/open-mmlab/mmcv/blob/master/docs/get_started/installation.md) and make sure it has been installed successfully.

**Comment by MeowZheng** [comment]
No further discussion

**Comment by Z-XQ** [comment]
> In this [part](https://github.com/open-mmlab/mmflow/blob/master/docs/install.md#prepare-environment), we have explained the cause of this problem. ![image](https://user-images.githubusercontent.com/76149310/142161702-9e0687f9-5932-42b3-a903-71a6d8e7a85f.png)
> 
> In addition, please check out [mmcv installation documents](https://github.com/open-mmlab/mmcv/blob/master/docs/get_started/installation.md) and make sure mmcv-full has been installed successfully.

Thank you! I have solved this problem and Wrote a [blog](https://blog.csdn.net/jizhidexiaoming/article/details/121374364) to describe this.
