### ISSUE TITLE
Basic question about optical flow

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmflow#168]
I am new to the optical flow and have a basic question.

To learn to predict optical flow, we need the ground truth for supervision. My understanding is, for example, the TV-L1. But since the groud truth optical flow can be computed by a non-CNN algorith,, why we should use a CNN to estimate the optical flow? Is that much faster than the non-CNN method?

**Comment by MeowZheng** [comment]
The precision of CNN method is much better than non-CNN method, and as there are some GPU-accelerated libraries of CNN like cudnn,  Some CNN methods are real-time and the speed of CNN method will be further improved.

**Comment by makecent** [comment]
@MeowZheng Thanks for your explanation. After literature review, I found that except for the speed. The ground truth of optical flow is NOT generated by a non-CNN method, otherwise the CNN learning from such labels can only be as good as the non-CNN method that used to generate the ground truth. Instead, the optical flow ground truth is naturally known because the videos in datasets are synthesized.
