### ISSUE TITLE
little bug

### ISSUE THREAD

**Issue by 459737087** [open-mmlab/mmflow#20]
during dataset download wegt https://lmb.informatik.uni-freiburg.de/data/FlyingChairs/FlyingChairs.zip,
remember to change wegt to wget

in mmflow/docs/dataset_prepare.md

**Comment by 459737087** [comment]
and wget http://files.is.tue.mpg.de/sintel/MPI-Sintel-complete.zip this url can't download dataset

**Comment by MeowZheng** [comment]
We are fixxing the bug in `dataset prepar`.

I just check the url and can download the dataset via  http://files.is.tue.mpg.de/sintel/MPI-Sintel-complete.zip

**Comment by 459737087** [comment]
Thank you !! @MeowZheng
