### ISSUE TITLE
The support of C++ project

### ISSUE THREAD

**Issue by zhanghua7099** [open-mmlab/mmflow#24]
Hi! Thank you for your good work!

Will this work support the use of C++? If not, could you give me some advice about the deployment method for the C++ project?

**Comment by MeowZheng** [comment]
MMFlow is based on Python. 

If you would like to use it in a C++ project, you can extract flow and save it by using  MMFlow, and apply the saved flow file in your project.

**Comment by MeowZheng** [comment]
No further discussion.
