### ISSUE TITLE
mmcv 1.7.0 not supported

### ISSUE THREAD

**Issue by JamesYang-7** [open-mmlab/mmflow#264]
I first installed mmflow 0.5.1 and then mmcv using command
`mim install mmcv`
but it reported
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mmflow 0.5.1 requires mmcv-full<1.7.0,>=1.3.15, but you have mmcv-full 1.7.0 which is incompatible.
```
And I tried to run the demo
```
   python demo/image_demo.py demo/frame_0001.png demo/frame_0002.png \
       configs/pwcnet/pwcnet_ft_4x1_300k_sintel_final_384x768.py \
       checkpoints/pwcnet_ft_4x1_300k_sintel_final_384x768.pth results
```
It reported that
`ModuleNotFoundError: No module named 'mmcv'`
I checked the installation using `pip list` and it showed mmcv-full is installed.
I'm using cuda-11.3 and pytorch-1.13.0

**Comment by MeowZheng** [comment]
please use master branch mmflow, we hanve midified the mmcv maximum version
https://github.com/open-mmlab/mmflow/blob/37be8939ba7896a18fc04d149aadd8c8fc7f0037/mmflow/__init__.py#L20
