### ISSUE TITLE
How to understand  "RepeatDataset"?

### ISSUE THREAD

**Issue by pedroHuang123** [open-mmlab/mmflow#265]
![image](https://user-images.githubusercontent.com/72126736/204207043-7135b370-673a-4b06-8db0-8177f0761812.png)
This method can reduce the data loading time between epochs.What do it mean?if my dataset is small,it's loading time is long between epochs,so is the args "times " bigger,the better?

**Comment by MeowZheng** [comment]
hi, 
I saw you have opened some issues very recently, and would you like to talk on wechat? I think it will be more efficient.

**Comment by MeowZheng** [comment]
During training, if the dataset is small, and the total training iteration is the same, the worker processes of dataloader will be launched at each epoch, and the time of launching processes is a little long. 

If we repeat several times, the dataset will become larger, and the total training iteration is the same, the epoch will become less and the time of launching processes will be acceptable.
