### ISSUE TITLE
Any plans on making MMDepth?

### ISSUE THREAD

**Issue by DianCh** [open-mmlab/mmflow#55]
Hi! Thanks for releasing such a wonderful toolbox. Given that MMSeg and MMFlow are in place, I wonder if there are any plans on making MMDepth that tackles depth estimation? I'd be very interested in using it.

**Comment by hellock** [comment]
We are planing this project indeed. However, it won't be finished in a short time due to the lack of developers. Collaborations are appreciated If you are interested in it.
