### ISSUE TITLE
Reopening - links broken again?

### ISSUE THREAD

**Issue by jhlusko** [open-mmlab/mmflow#59]
Reopening - links broken again?

_Originally posted by @jhlusko in https://github.com/open-mmlab/mmflow/issues/12#issuecomment-996459459_

**Comment by MeowZheng** [comment]
Could you please list broken links? I just checked links in README and all of them worked.

**Comment by chen-san** [comment]
model zoo links broken, https://github.com/open-mmlab/mmflow/blob/master/docs/configs/raft

**Comment by jhlusko** [comment]
Sorry about that, I'm looking for the checkpoints. I tried the links on this page: https://github.com/open-mmlab/mmflow/blob/55c4625e89e4d084f70f462974c66e67077672cd/docs/en/model_zoo.md

**Comment by MeowZheng** [comment]
sorry, I will fix it soon, and you can download the models via these links 
![image](https://user-images.githubusercontent.com/76149310/146499367-e6ff8dfa-04a5-4415-a3d2-1744dd44958f.png)

All checkpoints can be found in the model README
https://github.com/open-mmlab/mmflow/blob/master/configs/raft/README.md#results-and-models

**Comment by chen-san** [comment]
get, thx!
