### ISSUE TITLE
where is model()'s output?

### ISSUE THREAD

**Issue by zhanghahah1993** [open-mmlab/mmflow#69]
i need that:
    img = torch.rand(1, 6, 640,640).cuda()
    output1 = model(img)
but the output is a dict,where can i modify this to a tensor?

**Comment by MeowZheng** [comment]
the output is the loss with `dict` type, when model training. You can refer to https://github.com/open-mmlab/mmflow/blob/c458f8d92f49752acf5f994f74fa3bb5bacab3cf/mmflow/models/flow_estimators/pwcnet.py#L49-L67

If you would like to get the flow output, you can refer to these lines:
https://github.com/open-mmlab/mmflow/blob/c458f8d92f49752acf5f994f74fa3bb5bacab3cf/mmflow/apis/inference.py#L132-L143

**Comment by MeowZheng** [comment]
no further discussion
