### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by btgraham** [open-mmlab/mmflow#91]
Hello. Some of the URLs in the model zoo, i.e. 
https://github.com/open-mmlab/mmflow/blob/master/configs/gma/README.md
have spaces in that break the URL, i.e.
```
https://download.openmmlab.com/mmflow/gma/ gma_8x2_120k_mixed_368x768.py
```
instead of 
```
https://download.openmmlab.com/mmflow/gma/gma_8x2_120k_mixed_368x768.py
```

**Comment by MeowZheng** [comment]
Thanks for you reporting this bug.
